// ── SHARED MUTABLE STATE ──
export const state = {
  GAMES_BASE: [],
  TEAMS: {},
  EQUIPA_CLUBE: {},
  EQUIPA_ALOJAMENTO: {},
  TRANSPORTS: [],
  ALIMENTOS: [],
  fbResults: {},
  currentGames: [],
  profile: JSON.parse(localStorage.getItem('summercup_profile_andre') || 'null'),
  activeEscalao: '',
  activeDia: 'todos',
  activeLogDia: null,
  classFase: '2',
  classEscalao: '',
  classSerie: '',
  classFinalSub: 'todos',
  classMelhorTier: 1,
  currentResultGame: null,
  currentSets: [],
  dataLoaded: false,
};
